services:
  flask:
    build: 
      context: https://github.com/Chreece/GuestDoor.git
    container_name: flask
    environment:
      - DB_HOST=postgres
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_NAME=passcodes
      - API_SECRET=${API_SECRET}
      - HA_WEBHOOK=${HA_WEBHOOK}
    env_file:
      - .env
    ports:
      - "${PORT}:5000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app_network

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: passcodes
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d postgres"]
      interval: 5s
      retries: 5
      timeout: 3s

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
